version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: npm ci
        run:
          environment:
            CYPRESS_GMAIL_CREDENTIALS: ${{CYPRESS_GMAIL_CREDENTIALS}}
            CYPRESS_GMAIL_TOKEN: ${{CYPRESS_GMAIL_TOKEN}}
          command: |
            echo $CYPRESS_GMAIL_CREDENTIALS > CREDENTIALS.json
            echo $CYPRESS_GMAIL_TOKEN > TOKEN.json